- name: Install requirements
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - cron
      - gnupg-agent
    state: present

- name: Add Azlux repository
  deb822_repository:
    name: azlux
    uris: https://packages.azlux.fr/debian/
    suites: "{{ ansible_distribution_release }}"
    components: main
    signed_by: https://azlux.fr/repo.gpg.key
  notify: Update apt cache

- name: Fetch Azlux repository
  meta: flush_handlers

- name: Install Rclone
  package:
    name: rclone
    state: present

- name: Template script
  template:
    src: backup.sh.j2
    dest: /etc/backup.sh
    mode: "0700"
  notify: Backup

- name: Set crontab for backup
  cron:
    name: "backup"
    user: root
    minute: "{{ backup.schedule.minute }} "
    hour: "{{ backup.schedule.hour }} "
    day: "{{ backup.schedule.day }} "
    weekday: "{{ backup.schedule.weekday }} "
    month: "{{ backup.schedule.month }} "
    job: "/bin/bash /etc/backup.sh > /dev/null 2>&1"
